wandb_version: 1

C:
  desc: null
  value: 1.0
_wandb:
  desc: null
  value:
    cli_version: 0.9.1
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.6
penalty:
  desc: null
  value: l1
tol:
  desc: null
  value: 0.001
